version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: on-failure
    command: >
      sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:14.1
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./client:/usr/share/nginx/html/frontend
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/usr/share/nginx/html/doc